require "./libs/cblas"
require "./libs/lapack"
require "./libs/clblast"

require "complex"

require "./extensions/array"
require "./extensions/number"

require "./tensor/internal/shape"
require "./tensor/internal/broadcast"
require "./tensor/internal/print"
require "./tensor/internal/enums"
require "./tensor/internal/random"

require "./tensor/data_structure"
require "./tensor/allocation"
require "./tensor/iteration"
require "./tensor/index"
require "./tensor/manipulate"
require "./tensor/math"
require "./tensor/convert"
require "./tensor/random"

require "./tensor/backends/util_storage"
require "./tensor/backends/util_manipulate"
require "./tensor/backends/util_index"

require "./tensor/backends/hostptr/unsafe_iter"
require "./tensor/backends/hostptr/yield_iterators"

require "./tensor/backends/cpu/impl_allocation"
require "./tensor/backends/cpu/impl_manipulate"
require "./tensor/backends/cpu/impl_iteration"
require "./tensor/backends/cpu/impl_index"
require "./tensor/backends/cpu/impl_math"
require "./tensor/backends/cpu/impl_data_structure"
require "./tensor/backends/cpu/impl_convert"

require "./tensor/backends/opencl/kernels/cache"
require "./tensor/backends/opencl/kernels/templates"
require "./tensor/backends/opencl/kernels/custom"
require "./tensor/backends/opencl/private/global_state"
require "./tensor/backends/opencl/impl_allocation"
require "./tensor/backends/opencl/impl_data_structure"
require "./tensor/backends/opencl/impl_convert"
require "./tensor/backends/opencl/impl_math"
require "./tensor/backends/opencl/impl_index"
require "./tensor/backends/opencl/impl_manipulate"

require "./linalg/extension"
require "./linalg/work"
require "./linalg/linalg"

require "./grad/primitives/context"
require "./grad/primitives/gate"
require "./grad/primitives/node"
require "./grad/primitives/payload"
require "./grad/primitives/variable"
require "./grad/gates/arithmetic"
require "./grad/gates/blas"
require "./grad/gates/exp"
require "./grad/gates/trigonometric"
require "./grad/backends/agnostic"
require "./grad/backends/cpu"
require "./grad/backends/opencl"
require "./grad/variable.cr"

require "./nn/datasets/datasets"
require "./nn/datasets/iris"
require "./nn/datasets/mnist"
require "./nn/initialization"

require "./nn/backends/cpu/activation"
require "./nn/backends/opencl/activation"

require "./num/exceptions"
require "./num/aliases"
